import{initializeApp}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";import{getFirestore,collection,getDocs,addDoc,updateDoc,deleteDoc,doc}from"https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
/* ================= FIREBASE: COLE SUA CHAVE AQUI ================= */
const firebaseConfig={apiKey:"COLE_SUA_API_KEY_AQUI",authDomain:"SEU-PROJETO.firebaseapp.com",projectId:"SEU-PROJETO",storageBucket:"SEU-PROJETO.firebasestorage.app",messagingSenderId:"SEU_MESSAGING_SENDER_ID",appId:"SEU_APP_ID"};
/* ================================================================ */
const TARGET=42.24;let db=null,clients=[],products=[],tables=[];const $=id=>document.getElementById(id),money=n=>(+n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"}),pct=n=>(+n||0).toFixed(2).replace(".",",")+"%";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));const mar=(r,c)=>r?((r-c)/r)*100:0;const tab=id=>tables.find(t=>t.id===id);
function msg(t,err=false){$("msg").className="msg "+(err?"err":"");$("msg").textContent=t;setTimeout(()=>$("msg").textContent="",3500)}
function finance(c,override){let t=tab(override||c.tableId),rev=+c.monthlyRevenue||0;if(!t)return{rev,cost:0,profit:rev,margin:100,table:null};let ps=products.filter(p=>t.prices&&t.prices[p.id]!=null);if(!ps.length)return{rev,cost:0,profit:rev,margin:100,table:t};let sell=ps.reduce((a,p)=>a+(+t.prices[p.id]||0),0)/ps.length,cost=ps.reduce((a,p)=>a+(+p.cost||0),0)/ps.length;let co=sell?rev*(cost/sell):rev;return{rev,cost:co,profit:rev-co,margin:mar(rev,co),table:t}}
function portfolio(oid,ot){let rev=0,cost=0;clients.forEach(c=>{let f=finance(c,c.id===oid?ot:null);rev+=f.rev;cost+=f.cost});return{rev,cost,profit:rev-cost,margin:mar(rev,cost)}}
async function load(){if(firebaseConfig.projectId.startsWith("SEU-")||firebaseConfig.apiKey==="COLE_SUA_API_KEY_AQUI"){render();msg("Configure o firebaseConfig no app.js para salvar no Firebase.",true);return}try{db=getFirestore(initializeApp(firebaseConfig));let[a,b,c]=await Promise.all([getDocs(collection(db,"clientes")),getDocs(collection(db,"produtos")),getDocs(collection(db,"tabelas_preco"))]);clients=a.docs.map(x=>({id:x.id,...x.data()}));products=b.docs.map(x=>({id:x.id,...x.data()}));tables=c.docs.map(x=>({id:x.id,...x.data()}));render()}catch(e){console.error(e);msg("Erro ao carregar Firebase: "+e.message,true)}}
async function save(col,data,id){if(!db)throw Error("Firebase não configurado");if(id)await updateDoc(doc(db,col,id),data);else await addDoc(collection(db,col),data)}async function del(col,id){if(!db)throw Error("Firebase não configurado");await deleteDoc(doc(db,col,id))}
function render(){dash();clientsView();productsView();tablesView();simView();reportView();}
function dash(){let s=portfolio();$("rev").textContent=money(s.rev);$("cost").textContent=money(s.cost);$("profit").textContent=money(s.profit);$("mar").textContent=pct(s.margin);let g=s.margin-TARGET;$("gap").textContent=(g>=0?"+":"")+g.toFixed(2).replace(".",",")+" p.p.";$("ncli").textContent=clients.length;let q=($("ds")?.value||"").toLowerCase();$("dashRows").innerHTML=clients.filter(c=>(c.name||"").toLowerCase().includes(q)).map(c=>{let f=finance(c);return`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(f.table?.name||"Sem tabela")}</td><td>${money(f.rev)}</td><td>${money(f.cost)}</td><td class="${f.margin>=TARGET?"good":"low"}">${pct(f.margin)}</td></tr>`}).join("")||`<tr><td colspan="5" class="empty">Nenhum cliente.</td></tr>`}
function clientsView(){let old=$("ct").value;$("ct").innerHTML='<option value="">Todas as tabelas</option>'+tables.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("");$("ct").value=old;let q=($("cs")?.value||"").toLowerCase(),f=$("ct").value;$("clientRows").innerHTML=clients.filter(c=>(`${c.name} ${c.document||""}`).toLowerCase().includes(q)&&(!f||c.tableId===f)).map(c=>{let x=finance(c);return`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(c.document||"-")}</td><td>${esc(x.table?.name||"Sem tabela")}</td><td>${money(c.monthlyRevenue)}</td><td class="${x.margin>=TARGET?"good":"low"}">${pct(x.margin)}</td><td><div class="actions"><button onclick="clientModal('${c.id}')">Editar</button><button class="danger" onclick="removeClient('${c.id}')">Excluir</button></div></td></tr>`}).join("")||`<tr><td colspan="6" class="empty">Nenhum cliente.</td></tr>`}
function productsView(){let q=($("ps")?.value||"").toLowerCase();$("productRows").innerHTML=products.filter(p=>(`${p.name} ${p.category||""}`).toLowerCase().includes(q)).map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${esc(p.category||"-")}</td><td>${esc(p.unit||"m²")}</td><td>${money(p.cost)}</td><td><button onclick="productModal('${p.id}')">Editar</button> <button class="danger" onclick="removeProduct('${p.id}')">Excluir</button></td></tr>`).join("")||`<tr><td colspan="5" class="empty">Nenhum produto.</td></tr>`}
function tablesView(){let q=($("ts")?.value||"").toLowerCase();$("tableRows").innerHTML=tables.filter(t=>(t.name||"").toLowerCase().includes(q)).map(t=>{let ps=products.map(p=>{let v=t.prices?.[p.id];if(v==null)return"";let m=mar(v,p.cost);return`<div class="price"><small>${esc(p.name)}</small><b>${money(v)}</b><small class="${m>=TARGET?"good":"low"}">${pct(m)}</small></div>`}).join("");return`<div class="table-card"><div class="table-head"><h3>${esc(t.name)}</h3><span><button onclick="tableModal('${t.id}')">Editar</button> <button class="danger" onclick="removeTable('${t.id}')">Excluir</button></span></div><div class="price-grid">${ps||'<div class="empty">Sem preços definidos.</div>'}</div></div>`}).join("")||'<div class="panel empty">Nenhuma tabela.</div>'}
function simView(){let oc=$("sc").value,ot=$("st").value;$("sc").innerHTML=clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join("");$("st").innerHTML=tables.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join("");if(clients.some(c=>c.id===oc))$("sc").value=oc;if(tables.some(t=>t.id===ot))$("st").value=ot;simCalc()}
function simCalc(){let c=clients.find(x=>x.id===$("sc").value),tid=$("st").value,a=portfolio(),f=c?finance(c,tid):null,n=c?portfolio(c.id,tid):a;$("sm0").textContent=pct(a.margin);$("smc").textContent=pct(f?.margin||0);$("sm1").textContent=pct(n.margin);let d=n.margin-a.margin;$("smp").textContent=(d>=0?"+":"")+d.toFixed(2).replace(".",",")+" p.p."}
function reportView(){let total=portfolio().rev;$("reportRows").innerHTML=clients.map(c=>{let f=finance(c);return`<tr><td><strong>${esc(c.name)}</strong></td><td>${esc(f.table?.name||"Sem tabela")}</td><td>${money(f.rev)}</td><td>${money(f.cost)}</td><td>${money(f.profit)}</td><td>${pct(f.margin)}</td><td>${pct(total?f.rev/total*100:0)}</td></tr>`}).join("")||`<tr><td colspan="7" class="empty">Nenhum cliente.</td></tr>`}
function modal(html,submit){$("form").innerHTML=html;$("modal").classList.add("show");$("form").querySelector("form").onsubmit=submit}window.closeModal=()=>$("modal").classList.remove("show");
window.clientModal=(id)=>{let c=id?clients.find(x=>x.id===id):{};modal(`<form class="form"><h2>${id?"Editar":"Novo"} cliente</h2><label>Nome<input name="name" required value="${esc(c.name||"")}"></label><label>CPF/CNPJ<input name="document" value="${esc(c.document||"")}"></label><label>Faturamento médio mensal<input name="monthlyRevenue" type="number" step=".01" required value="${c.monthlyRevenue??""}"></label><label>Tabela<select name="tableId"><option value="">Sem tabela</option>${tables.map(t=>`<option value="${t.id}" ${c.tableId===t.id?"selected":""}>${esc(t.name)}</option>`).join("")}</select></label><div class="form-actions"><button type="button" onclick="closeModal()">Cancelar</button><button class="primary">Salvar</button></div></form>`,async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.monthlyRevenue=+d.monthlyRevenue||0;try{await save("clientes",d,id);if(id)clients=clients.map(x=>x.id===id?{id,...d}:x);else{let s=await getDocs(collection(db,"clientes"));clients=s.docs.map(x=>({id:x.id,...x.data()}))}closeModal();render();msg("Cliente salvo.")}catch(e){msg(e.message,true)}})};
window.removeClient=async id=>{if(!confirm("Excluir cliente?"))return;try{await del("clientes",id);clients=clients.filter(x=>x.id!==id);render();msg("Cliente excluído.")}catch(e){msg(e.message,true)}};
window.productModal=(id)=>{let p=id?products.find(x=>x.id===id):{};modal(`<form class="form"><h2>${id?"Editar":"Novo"} produto</h2><label>Produto<input name="name" required value="${esc(p.name||"")}"></label><label>Categoria<input name="category" value="${esc(p.category||"")}"></label><label>Unidade<input name="unit" value="${esc(p.unit||"m²")}"></label><label>Custo<input name="cost" type="number" step=".01" required value="${p.cost??""}"></label><div class="form-actions"><button type="button" onclick="closeModal()">Cancelar</button><button class="primary">Salvar</button></div></form>`,async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target));d.cost=+d.cost||0;try{await save("produtos",d,id);if(id)products=products.map(x=>x.id===id?{id,...d}:x);else{let s=await getDocs(collection(db,"produtos"));products=s.docs.map(x=>({id:x.id,...x.data()}))}closeModal();render();msg("Produto salvo.")}catch(e){msg(e.message,true)}})};
window.removeProduct=async id=>{if(!confirm("Excluir produto?"))return;try{await del("produtos",id);products=products.filter(x=>x.id!==id);render();msg("Produto excluído.")}catch(e){msg(e.message,true)}};
window.tableModal=(id)=>{let t=id?tables.find(x=>x.id===id):{};modal(`<form class="form"><h2>${id?"Editar":"Nova"} tabela</h2><label>Nome da tabela<input name="name" required value="${esc(t.name||"")}"></label>${products.map(p=>`<label>${esc(p.name)} — custo ${money(p.cost)}<input name="p_${p.id}" type="number" step=".01" placeholder="Preço de venda" value="${t.prices?.[p.id]??""}"></label>`).join("")}<div class="form-actions"><button type="button" onclick="closeModal()">Cancelar</button><button class="primary">Salvar</button></div></form>`,async e=>{e.preventDefault();let fd=new FormData(e.target),prices={};products.forEach(p=>{let v=fd.get("p_"+p.id);if(v!=="")prices[p.id]=+v});let d={name:fd.get("name"),prices};try{await save("tabelas_preco",d,id);if(id)tables=tables.map(x=>x.id===id?{id,...d}:x);else{let s=await getDocs(collection(db,"tabelas_preco"));tables=s.docs.map(x=>({id:x.id,...x.data()}))}closeModal();render();msg("Tabela salva.")}catch(e){msg(e.message,true)}})};
window.removeTable=async id=>{if(clients.some(c=>c.tableId===id)){alert("Esta tabela está atribuída a clientes. Troque esses clientes de tabela antes de excluir.");return}if(!confirm("Excluir tabela?"))return;try{await del("tabelas_preco",id);tables=tables.filter(x=>x.id!==id);render();msg("Tabela excluída.")}catch(e){msg(e.message,true)}};
$("apply").onclick=async()=>{let c=clients.find(x=>x.id===$("sc").value),tid=$("st").value;if(!c||!tid)return;try{await save("clientes",{tableId:tid},c.id);c.tableId=tid;render();msg("Tabela aplicada ao cliente.")}catch(e){msg(e.message,true)}};
function csv(){let total=portfolio().rev,r=[["Cliente","Tabela","Faturamento","Custo","Lucro","Margem","Participação"]];clients.forEach(c=>{let f=finance(c);r.push([c.name,f.table?.name||"",f.rev.toFixed(2),f.cost.toFixed(2),f.profit.toFixed(2),f.margin.toFixed(2),total?(f.rev/total*100).toFixed(2):"0"])});let b=new Blob(["\ufeff"+r.map(x=>x.map(v=>`"${String(v).replaceAll('"','""')}"`).join(";")).join("\n")],{type:"text/csv"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="cubo_glass_margem.csv";a.click()}window.csv=csv;
["ds","cs","ct","ps","ts"].forEach(id=>$(id).oninput=render);$("ct").onchange=render;$("sc").onchange=simCalc;$("st").onchange=simCalc;document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(b.dataset.p).classList.add("active")});render();load();
